### ISSUE TITLE
Wrong default on bluefox_front

### ISSUE THREAD

**Issue by ghost** [ctu-mrs/mrs_uav_general#5]
- In file uav_core/ros_packages/mrs_uav_general/launch/sensors.launch
- In bluefox section 
- in bluefox_front subsection 

the arg camera_frame has a wrong default, according to the convention used with all the others: 
- It is:
`<arg name="camera_frame" default="bluefox_front" />`
- But it is expected to be:
`<arg name="camera_frame" default="$(arg UAV_NAME)/bluefox_front" />`

This is causing some issues with the reference frame transformations due to this wrong name,

**Comment by petrlmat** [comment]
Thanks for the report. Fixed in https://github.com/ctu-mrs/mrs_uav_general/commit/389713a6c8622fc20a1e4c11b6653ecca317bbc1. There were also some unused arguments, which caused incompatibility with the newest bluefox2 commit.
